# Generated by Django 2.1.1 on 2018-09-30 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_body', models.CharField(max_length=240)),
                ('cheerleader', models.CharField(max_length=60)),
                ('sent', models.BooleanField()),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Coaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_body', models.CharField(max_length=240)),
                ('previous_coaching_step', models.IntegerField()),
                ('run_event', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('url', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='RunEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=60)),
                ('event_date', models.DateTimeField()),
                ('distance', models.IntegerField()),
                ('goal_time', models.IntegerField()),
                ('cutoff_time', models.IntegerField()),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coaching.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='RunUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_body', models.CharField(max_length=240)),
                ('time_stamp', models.DateTimeField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coaching.RunEvent')),
            ],
        ),
        migrations.AddField(
            model_name='cheer',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coaching.RunEvent'),
        ),
    ]
