# Generated by Django 2.1.1 on 2018-09-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaching',
            name='previous_coaching_step',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='runevent',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='runevent',
            name='event_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='runevent',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='runevent',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='runevent',
            name='stop_time',
            field=models.DateTimeField(null=True),
        ),
    ]
