# Generated by Django 2.1.1 on 2018-09-30 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0003_auto_20180929_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runevent',
            name='city',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='runevent',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='runevent',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coaching.Picture'),
        ),
        migrations.AlterField(
            model_name='runevent',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
